"""
A basic introduction.
"""
name = "Josh"
language = "Python"

print(f"Hello, World! I'm {name}. I'm testing autogenerated release notes using a {favorite_language} script.")

"""
Basic math to teach the youth.
"""
value = 2
print(f"{value} plus by 2 is: {value * 2}")
